resolver: lts-15.6

packages:
  - .

extra-deps:
  # - chart-svg-0.0.2
  - git: https://github.com/tonyday567/chart-svg
    commit: b1ecb513ec498a516b2eb72ea47a8082477d04b3
  # - box-0.3.0
  # tolist branch (box-0.3.0 + appendCommitter experiment)
  - git: https://github.com/tonyday567/box
    commit: 8379b7efd7292878fd51b98128eff9313c557a61
  # uses box tolist branch
  - git: https://github.com/tonyday567/online-csv
    commit: a10b279e8f232fbe3aa92bd96960d06ade04cee6
  - numhask-array-0.5.1
  - numhask-prelude-0.3.3
  - numhask-space-0.3.1
  - online-0.4.0.0
  - perf-0.5.0.0
  - perf-analysis-0.2.0.0
  - readme-lhs-0.5.0
  - web-rep-0.4.0
  # external non-stack libraries
  - backprop-0.2.6.3
  - interpolatedstring-perl6-1.0.2
  - javascript-bridge-0.2.0
  - lucid-svg-0.7.1
  - tdigest-0.2.1
  - text-format-0.3.2
allow-newer: true
