resolver: lts-15.6

packages:
  - .

extra-deps:
  - backprop-0.2.6.3
  - box-0.2.0
  # - chart-svg-0.0.1
  - git: https://github.com/tonyday567/chart-svg
    commit: 436afe6d9f49782200d5d851fc8a36e330ddef8e
  - interpolatedstring-perl6-1.0.2
  - javascript-bridge-0.2.0
  - lucid-svg-0.7.1
  - numhask-array-0.5.1
  - numhask-prelude-0.3.3
  - numhask-space-0.3.1
  - online-0.4.0.0
  - perf-0.5.0.0
  - perf-analysis-0.2.0.0
  - readme-lhs-0.5.0
  - tdigest-0.2.1
  - text-format-0.3.2
  # - web-rep-0.3.1
  - git: https://github.com/tonyday567/online-csv
    commit: 67844ac0a80d2082b805554c79bd061c2fa85750
  - git: https://github.com/tonyday567/web-rep
    commit: 0863a2974af30ece6cb46fb8a1198cb9b053c5e2
allow-newer: true
