resolver: lts-15.6

packages:
  - .

extra-deps:
  - backprop-0.2.6.3
  - box-0.2.0
  - chart-svg-0.0.1
  - interpolatedstring-perl6-1.0.2
  - javascript-bridge-0.2.0
  - lucid-svg-0.7.1
  - numhask-array-0.5.1
  - numhask-prelude-0.3.3
  - numhask-space-0.3.1
  - online-0.4.0.0
  - palette-0.3.0.2
  - perf-0.5.0.0
  - perf-analysis-0.2.0.0
  - readme-lhs-0.5.0
  - tdigest-0.2.1
  - text-format-0.3.2
  - web-rep-0.3.1
  - git: https://github.com/tonyday567/online-csv
    commit: 67844ac0a80d2082b805554c79bd061c2fa85750

allow-newer: true
